### PR TITLE
allow the use of non-secure websockets

### PR DESCRIPTION
**Pull request by ntraut**
Secure web-sockets are not easy to set up. I propose to preserve the support of non-secure web-sockets if not too difficult to maintain.

---

- [ ] These changes fix #__ (github issue number if applicable).
- [ X ] ```npm run mocha-test``` ran with full success.
- [ ] ```npm run mocha-test``` ran resulted in  failure in _____

- [ ] I implemented tests for the changes I made OR
- [ X ] These changes do not require tests because no new feature

- [ X ] All BrainBox tools behave as expected:
except save button displays a message that user needs to login in case they are not (unless I missed it)
    * **KEYS**
        * right and left arrow keys
            - [ ] jump to next or previous slice within one brain, respectively
            - [ ] update the slider accordingly
            - [ ] update the slice number accordingly (upper left corner of the viewer window)
        * down and up arrow keys
            - [ ] jump to the next or previous brain within one project, respectively
            - [ ] update the selected subject in the annotation table
    * **TOOL BUTTONS**
        * minus
            - [ ] jumps to the previous slice within one brain
            - [ ] updates the slider accordingly
            - [ ] updates the slice number accordingly (upper left corner of the viewer window)
        * plus
            - [ ] jumps to the next slice within one brain
            - [ ] updates the slider accordingly
            - [ ] updates the slice number accordingly (upper left corner of the viewer window)
        * slider
            - [ ] updates slice view and slice number on the fly
        * sag / cor / axi buttons
            - [ ] switch view between the three orthogonal planes
        * show tool
            - [ ] when you click and drag in your browser window, this tool displays a cirlce at the position of your mouse click & drag as well as the user name in all browser windows connected to the same brain
        * the numbers at the bottom of the tool panel
            - [ ] change pencil size and eraser size accordingly
        * pencil tool
            - [ ] draws a line in the colour displayed in the color field
            - [ ] in combination with bucket tool filles a complete area with the chosen colour (be sure to have closed the contour line ;) Otherwise, the undo button will be your friend ;)
            - [ ] updates length and volume information (of what has been segmented) in the upper left corner of the viewer
        * erase tool
            - [ ] erases upon click drag from the annotation
            - [ ] in combination with the bucket tool erases the complete area of the color where you click
        * fill bucket tool
            * in combination with pencil tool
                - [ ] fills a complete area with the colour displayed in the colour field
            * in combination with erase tool
                - [ ] erases the complete area that is filled by the colour of where you click
        * colour field
            - [ ] displays the currently chosen colour to draw and fill
            - [ ] on click opens the set of colours available within the chosen label set where a new colour can be selected upon click
        * ruler tool
            - [ ] measures the distance between start and end of your defined path
                - [ ] points of mouse click appear and stay visible until you hit return key (this functionality is currently broken!) (you can click as many points as you wish to define the path you are interested in)
                - [ ] on return key, BrainBox will print the distance into the chat field (the ruler tool seems to be currently broken!!!)
        * adjust tool
            - [ ] slide opacity of overlaid annotation from 0 to 100%
            - [ ] increase or decrease brightness of the underlying MRI data
            - [ ] increase or decrease the contrast of the underlying MRI data
        * eyedropper tool
            - [ ] updates the colour field in the tool panel
            - [ ] displays/updates the region name in the upper left corner of the viewer
        * undo tool
            - [ ] undoes the user's actions in reverse chronological order and currently has the bug that it even undoes actions in slices you are currently not seeing! and there is currently no redo...
        * save button
            - [ ] saves the annotation of the data set into the data base
            - [ ] displays a message that user needs to login in case they are not
            - [ ] display a message `Atlas saved Wed Oct 18 2017 12:49:12 GMT+0200 (CEST)`

### CODE REVIEW

**Comment by r03ert0** [comment]
other than that, it looks great! It'll be nice to have plain ws for local testing : )

**Comment by ntraut** [comment]
Do you mean for node or ESLint?
For node it is perfectly ok:
```
> datadir = "./test/data/bar/foo"
'./test/data/bar/foo'
> datadir.split("/")[2]
'data'
> [,, datadir] = datadir.split("/");
[ '.', 'test', 'data', 'bar', 'foo' ]
> datadir
'data'
```
For ESLint I don't find their explanations very clear. They say not to do it for `var foo = array[100];`, that's obvious the code would look pretty ugly, but they don't say what to do for small numbers. If we keep `datadir.split("/")[2]` we have a warning. I saw the same issue for an index like 5, I did not touch but I don't know what to do to suppress the warning. Maybe we could do something like that:
`var {2: datadir} = datadir.split("/");`
https://medium.com/the-andela-way/this-trick-will-help-you-de-structure-javascript-arrays-in-a-better-cleaner-way-a3bbc39ce226

**Comment by r03ert0** [comment]
It seems jquery returns 'array-like' objects which are not really arrays, and array destructuring doesn't work in those cases. This is the example from the eslint website:

```
var $ = require('jquery');
var foo = $('body')[0];
var [bar] = $('body'); // fails with a TypeError
```
In all other cases when you are dealing with normal arrays, destructuring is :+1: :)

**Comment by ntraut** [comment]
Ok, I did not look at the right file so.
I cannot reproduce the error and ESLint gives a warning with `var foo = $('body')[0];`.
Maybe for more safety we could add `Array.from`: `var [bar] = Array.from($('body'));`?

**Comment by r03ert0** [comment]
actually, the best would be maybe just to drop jquery.
In vanilla JS there's two functions to query objects: document.querySelector("body") will query a single "body" element (and there should be only one, so that's what we want). For elements that may be more than once, there's document.queryAllSelectors("div"), for example, which gives an array (or array-like?) with all elements that match the selector (div in this case).

Could you try `me.canvas = me.container.querySelector('canvas');` and see if it works?

it may not work if me.container is a jquery object...

if that's the case, jquery allow you to do `me.container.find('canvas').get(0)`... but I'd be very happy to get rid of all the jquery, little by little :p

thank you !!!

**Comment by ntraut** [comment]
I replaced some jquery, I hope I did not break anything :D

**Pull request merged**
