### PR TITLE
Cleanup and Enhancement: Todo tasks completed, code cleaned up and nodemon added.

### LINKED ISSUE #274: Feature Request/Cleanup: Remove redundant todo tasks and use nodemon to speed up the dev process.
The feature request consists of the following points:
- Currently a lot of todo tasks have accumulated in the repository. These tasks need to be completed and stray todo marks be removed.
- findOne() method should be used instead of find() to speed up checks and access to data.
- We can use nodemon to launch the server instead of node. This speeds up the process and saves the developers from constant manual restart of the server.

P.S: I am linking the PR to this as well.
@katjaq @r03ert0 
Kindly have a look if this aligns with our objectives.

### PR DESCRIPTION
**Pull request by adityaofficial10**
Fixes #274 
**What does this PR do?**
- Redundant todo comments removed.
- find() replaced by findOne() wherever required.
- Nodemon added as a dev dependency and added in the start script.

@katjaq @r03ert0 
Kindly review the changes and add this task as completed in our project.
Best Regards..

### CODE REVIEW

**Comment by r03ert0** [comment]
thank you for this @adityaofficial10 !
changes to the frontend require `npm run build`. `nodemon` will just lunch the server again but will not rebuild, no? I think there's a way of making webpack rebuild on the fly, which would be a better alternative? Also, when running the tests, there are some files written to the `screenshots` folder. This may hint `nodemon` to rerun the server? Finally, we use visual studio code for development, and it frequently checks github for updates, which also writes a local file. This may also trigger a `nodemon` restart?

**Comment by adityaofficial10** [comment]
Hey @r03ert0 @katjaq !
I suggest using watch for keeping track of the frontend files and whenever a change is made there, we can run the webpack build and when that finishes, nodemon can restart the server.
I've figured out a way to ensure nodemon restarts after the webpack build is finished.
This will make the development easier for the developer as it saves the time to manually close and restart everything.
Does this sound good?
Best Regards...

**Comment by r03ert0** [comment]
let's try it! \o/

**Comment by adityaofficial10** [comment]
@r03ert0
Thanks a lot.
I'd quickly send a patch for review.
Best Regards..

**Pull request merged**
