### PR TITLE
Using components from the `nwl-components` library

### PR DESCRIPTION
**Pull request by dhovart**
This PR uses the Vue components I've created here : https://github.com/dhovart/nwl-components
They're set to be similar in style and to behave the same as what is currently existing.

The idea is to reuse the same components for both microdraw and brainbox (and to provide building block for coming up with custom components).
A config file is used to provide site-specific information and customization.

Just the settings, new project and user pages have been set to use them for now.
For the project page, it requires much more effort to move everything to Vue.

### CODE REVIEW

**Comment by dhovart** [comment]
It would be great if you could test locally and make sure the styles and behaviours are what you expect before merging.

**Comment by dhovart** [comment]
@katjaq @ntraut @r03ert0 let me know if the tests relying on the DOM seem correct to you.

**Comment by ntraut** [comment]
> @katjaq @ntraut @r03ert0 let me know if the tests relying on the DOM seem correct to you.

for me it's better like this. not sure that all the important elements are evaluated but anyway we still can add some evaluations if we find something important missing. maybe it could be good to still produce the screenshots even if we don't use them for the evaluation, just to have a simple visual way of checking if something went wrong.

**Comment by dhovart** [comment]
It defaults to a timeout of 30000ms. I think it's a good thing if it fails
because the selector was not encountered.
You can shorten the timeout of you think it's better.

Em qua., 2 de mar. de 2022 14:25, Nicolas Traut ***@***.***>
escreveu:

**Comment by ntraut** [comment]
indeed, i looked at the mocha timeout which is sometimes set to 0 but the puppeteer function itself has a default timeout of 30s, sorry about that miss

for me it is ok to merge

**Review by katjaq — APPROVED** [review]
That's fantastic!! Everything vue-ified now! The components are great. Looks great, too! Thanks so much @dhovart 
Thank you @ntraut for your review and feedback as well ! 
🚀 merging!

**Pull request merged**
