### PR TITLE
Fix #343

### LINKED ISSUE #343: newly added brains can only be viewed and segmented once until they are added to a project
the second time we try to access the brain we get a blank page with "Authorization required". we can access the brain again once it gets added to a project, even if the project rights for anyone are null.
this behaviour doesn't seem to make a lot of sense to me, so I think it's a bug.

### PR DESCRIPTION
**Pull request by dhovart**
Cf https://github.com/neuroanatomy/BrainBox/issues/343#issuecomment-1151029187

### CODE REVIEW

**Comment by ntraut** [comment]
This looks like the bug is fixed but should we write a test to reproduce the bug or is that ok if we simply fix it?

Also, I wonder if the description of the function `hasAccesstoFileIfAllowedBySomeProjects` is still relevant: https://github.com/neuroanatomy/BrainBox/blob/3d807378f53c03d45a974dcb5002a29847cc1232/services/BrainboxAccessControlService.js#L21-L34

Not sure also if the `privilegedAccessInfo` warning is still relevant:
https://github.com/neuroanatomy/BrainBox/blob/10ac79df1c387bd5dc0406042edf5dcf10db22fa/templates/mri.mustache#L53

There is also still the problem that even if the mri controller should no longer fail because of trying to get the property `shortname` of null, the errors are still not properly handled because it is an async function and express is not designed to automatically catch errors coming from promises.

**Comment by dhovart** [comment]
You're right about the test, I should introduce one to make sure we're not going to have regressions. Will do this first thing tomorrow.

Answered you earlier about the access control check in #343

I think it's a good thing to still have the warning in place. Of course you can now directly access the page if you know the URL but hopefully people will not share the address, because of this warning (it will only show if you're a collaborator to a project using it, and that no project allow anyone seeing files)

**Comment by r03ert0** [comment]
Keep the warning. @katja already had a case of a collaborator who unintentionally leaked the URL of an MRI that wasn't supposed to be shared (the collaborator added it to a public project).

**Comment by ntraut** [comment]
Maybe this bug is too specific to need to make a test for it: it happens when we load a test mri which is not part of a project but only from the second time.

It is the sentence "The MRI file is only accessible if some projects allow it" which no longer describes the actual behavior, but maybe it is not very important to have this imprecision in the description.

Also, in which case some files may use a 'source' property to store url? I looked in the brainbox db and did not find any...

What do you think we should do to handle promise rejections in express middlewares like mri controller. Should we add a catch block each time or use wrapper like [express-async-handler ](https://www.npmjs.com/package/express-async-handler)?

**Comment by ntraut** [comment]
> Also, in which case some files may use a 'source' property to store url? I looked in the brainbox db and did not find any...
Ah yes I didn't look well, it's in the case the file has a name in addition to its source.

**Comment by dhovart** [comment]
I think you're mixing up two methods documentation. The behaviour is still the same as it was and it says clearly: `if all projects allow it`.

It could be a good idea to introduce express-async-handler, yes.

**Comment by ntraut** [comment]
No with the fix the MRI files are accessible even if no project allows it, it is just the annotations from the private projects that we don't see.

For the possible `source` and `name` properties of files I'm still confused because I tried to add MRI to a project giving them names, and they are still stored as single string in the files list. Does it come from a previous behaviour which changed since? Would not it better to try to uniformize rather than dealing continuously with those special cases?

**Comment by dhovart** [comment]
But to me the fix is unrelated to this particular method, so I'm not sure what is your point.

I also was confused to see we both had both at times a list of object with the properties "source" and "name" and a list of strings. I attempted unifying it but the database may still not be consistent.

**Comment by dhovart** [comment]
Oh, I think I may get your point. I didn't understand it was a matter of semantics. What you're saying is that now the method name does no longer look correct to you, since we can access the files no matter what.

The method hasAccessToFile... does not tell you if you can directly access the MRI URL, it just compares the access level set as a parameter (view/add/remove etc.) and tells you if this specific access is set in settings as granted or not.

If I follow your logic we should remove this setting defining access to files since we can directly access a MRI if we know it's url. Is that correct?


Can you point me to where you see that people can change the name of a file defined in other projects? I think names are only stored in a project's settings.

**Comment by ntraut** [comment]
I was more thinking of the description in the jsdoc, but maybe also the function name doesn't fit very well anymore.

I think the files authorizations are more to tell if the users have the right to view/edit the list of the project files rather than viewing the files themselves, that may be the source of the confusion.

**Comment by ntraut** [comment]
> Can you point me to where you see that people can change the name of a file defined in other projects? I think names are only stored in a project's settings.

Sorry, i forgot to answer to that question. It's simple, now when people give a name for an mri in a project, it will be save in the mri collection. So if the mri is already used by another project, the name will be overwritten. I  don't really understand why it's designed like this.

**Comment by ntraut** [comment]
Hi @katjaq, he said that for his other pr that he created just to see the result of the ci. i will merge so, thanks @dhovart for those fixes!

**Pull request merged**
